# Generated by Django 5.1.3 on 2024-12-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
