# Generated by Django 5.1.3 on 2024-12-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_price'),
        ('subCategory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='category',
        ),
        migrations.AddField(
            model_name='package',
            name='subCategory',
            field=models.ManyToManyField(related_name='packageSubCategory', to='subCategory.subcategory'),
        ),
    ]
