# Generated by Django 5.1.3 on 2024-12-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_remove_package_category_package_subcategory'),
        ('subCategory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='subCategory',
        ),
        migrations.AddField(
            model_name='package',
            name='subCategories',
            field=models.ManyToManyField(related_name='packageSubCategories', to='subCategory.subcategory'),
        ),
    ]
