# Generated by Django 5.1.4 on 2024-12-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_alter_category_description"),
        ("packages", "0004_remove_package_subcategory_package_subcategories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="subCategories",
        ),
        migrations.AddField(
            model_name="package",
            name="categories",
            field=models.ManyToManyField(
                related_name="packageCategories", to="category.category"
            ),
        ),
    ]
