# Generated by Django 5.1.4 on 2024-12-20 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_description_alter_location_image'),
        ('packages', '0006_customization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='location',
        ),
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.CreateModel(
            name='PackageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='packages.package')),
            ],
        ),
    ]
