# Generated by Django 5.1.4 on 2024-12-20 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_description'),
        ('location', '0002_alter_location_description_alter_location_image'),
        ('packages', '0007_remove_package_location_remove_package_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageLocationPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_location_prices', to='packages.package')),
            ],
        ),
        migrations.DeleteModel(
            name='PackageLocation',
        ),
    ]
