# Generated by Django 5.1.4 on 2024-12-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_packagelocationprice_delete_packagelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='customizations',
            field=models.ManyToManyField(related_name='packageCustomizations', to='packages.customization'),
        ),
    ]
