# Generated by Django 5.1.4 on 2024-12-30 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_remove_category_location_category_location'),
        ('packages', '0009_package_customizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagelocationprice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_category', to='category.category'),
        ),
    ]
