# Generated by Django 5.1.4 on 2025-01-02 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_description_alter_location_image'),
        ('packages', '0010_alter_packagelocationprice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagelocationprice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_location', to='location.location'),
        ),
    ]
