# Generated by Django 5.1.4 on 2025-01-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_alter_packagelocationprice_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagelocationprice',
            name='category',
        ),
    ]
