# Generated by Django 5.1.4 on 2025-01-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_rename_locations_category_location'),
        ('location', '0002_alter_location_description_alter_location_image'),
        ('packages', '0012_remove_packagelocationprice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagelocationprice',
            name='category',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='package_category', to='category.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packagelocationprice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
