# Generated by Django 5.1.4 on 2025-01-02 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_packageinclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageinclusion',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='package_inclusion', to='packages.package'),
            preserve_default=False,
        ),
    ]
