# Generated by Django 5.1.4 on 2025-01-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_packageinclusion_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageinclusion',
            name='package',
        ),
        migrations.AddField(
            model_name='package',
            name='package_inclusion',
            field=models.ManyToManyField(related_name='packageInclusion', to='packages.packageinclusion'),
        ),
    ]
