# Generated by Django 5.1.4 on 2025-01-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0016_remove_packageinclusion_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageinclusion',
            name='description',
        ),
        migrations.AddField(
            model_name='packageinclusion',
            name='title',
            field=models.CharField(default='wsdd', max_length=255),
            preserve_default=False,
        ),
    ]
