# Generated by Django 5.1.4 on 2025-01-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0017_remove_packageinclusion_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='need_to_know',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='need_to_know',
            field=models.ManyToManyField(related_name='packageneed_to_know', to='packages.need_to_know'),
        ),
    ]
