# Generated by Django 5.1.4 on 2025-01-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0018_need_to_know_package_need_to_know'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='need_to_know',
        ),
    ]
