# Generated by Django 5.1.4 on 2025-01-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0019_remove_package_need_to_know'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='need_to_know',
            field=models.ManyToManyField(related_name='packageneed_to_know', to='packages.need_to_know'),
        ),
    ]
