# Generated by Django 5.1.4 on 2025-01-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0020_package_need_to_know'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='short_description',
            field=models.TextField(default='demo'),
            preserve_default=False,
        ),
    ]
