# Generated by Django 5.1.3 on 2024-11-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_adminprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
