# Generated by Django 5.1.4 on 2024-12-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('customer', 'Customer')], default='admin', max_length=10, null=True),
        ),
    ]
