# Generated by Django 5.1.4 on 2025-01-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_why_avenza'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancelation_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
