# Generated by Django 5.1.4 on 2024-12-25 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_image_category_banner_image_muliple_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='categories/banner_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_images', to='category.category')),
            ],
        ),
    ]
