# Generated by Django 5.1.4 on 2024-12-25 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_categorybannerimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='banner_image_muliple',
            new_name='banner_images',
        ),
        migrations.AlterField(
            model_name='categorybannerimage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_banner_images', to='category.category'),
        ),
    ]
