# Generated by Django 5.1.4 on 2024-12-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_rename_banner_image_muliple_category_banner_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='banner_images',
        ),
    ]
