# Generated by Django 5.1.4 on 2024-12-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_remove_category_banner_images'),
        ('location', '0002_alter_location_description_alter_location_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='location',
        ),
        migrations.AddField(
            model_name='category',
            name='location',
            field=models.ManyToManyField(related_name='categories', to='location.location'),
        ),
    ]
