# Generated by Django 5.1.4 on 2024-12-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_remove_category_location_category_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='location',
        ),
    ]
