# Generated by Django 5.1.4 on 2024-12-31 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_remove_category_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_category_image',
            new_name='category_image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='sub_category_title',
            new_name='sub_title_category',
        ),
    ]
