# Generated by Django 5.1.4 on 2025-01-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_rename_sub_category_image_category_category_image_and_more'),
        ('location', '0002_alter_location_description_alter_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='location',
            field=models.ManyToManyField(related_name='categories', to='location.location'),
        ),
    ]
