# Generated by Django 5.1.4 on 2025-01-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_category_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='location',
            new_name='locations',
        ),
    ]
