# Generated by Django 5.1.4 on 2025-01-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_rename_location_category_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='locations',
            new_name='location',
        ),
    ]
