# Generated by Django 5.1.3 on 2024-12-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
        ('subCategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='subCategories',
            field=models.ManyToManyField(related_name='sectionSubCategory', to='subCategory.subcategory'),
        ),
    ]
