# Generated by Django 5.1.4 on 2025-01-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_homesection_subcategories'),
        ('location', '0002_alter_location_description_alter_location_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebanner',
            name='location',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='location',
        ),
        migrations.AddField(
            model_name='homebanner',
            name='location',
            field=models.ManyToManyField(related_name='homeBannerLocation', to='location.location'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='location',
            field=models.ManyToManyField(related_name='homeSectionLocation', to='location.location'),
        ),
    ]
