# Generated by Django 5.1.4 on 2025-01-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_remove_homebanner_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesection',
            name='subCategories',
        ),
    ]
