# Generated by Django 5.1.4 on 2024-12-26 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('location', '0002_alter_location_description_alter_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerLocation', to='location.location'),
        ),
    ]
