# Generated by Django 5.1.4 on 2024-12-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_location'),
        ('customers', '0002_ticket'),
    ]

    operations = [
    ]
