# Generated by Django 5.1.3 on 2024-11-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='business_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
