# Generated by Django 5.1.3 on 2024-12-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendor_business_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='contact_number',
            new_name='vendorPhoneNumber',
        ),
    ]
