# Generated by Django 5.1.3 on 2024-12-14 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_description_alter_location_image'),
        ('vendors', '0005_rename_contact_number_vendor_vendorphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendorLocation', to='location.location'),
        ),
    ]
