# Generated by Django 5.1.4 on 2024-12-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_vendor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendorname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
