# Generated by Django 5.1.4 on 2024-12-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendor_vendorname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='business_name',
        ),
    ]
