# Generated by Django 5.1.4 on 2024-12-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_description'),
        ('vendors', '0008_remove_vendor_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
