# Generated by Django 5.1.4 on 2024-12-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0009_vendor_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="business_address",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="gst_number",
        ),
    ]
