# Generated by Django 5.1.4 on 2024-12-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_remove_vendor_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_images/'),
        ),
    ]
