# Generated by Django 5.1.4 on 2024-12-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='portfolio_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
