# Generated by Django 5.1.4 on 2024-12-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_vendor_portfolio_link_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
