# Generated by Django 5.1.4 on 2025-01-06 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_alter_vendoravailability_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCompletionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendor_order_completion/')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_completion_images', to='vendors.vendor')),
            ],
        ),
    ]
