# Generated by Django 5.1.4 on 2025-01-06 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0017_ordercompletionimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercompletionimage',
            old_name='image',
            new_name='completion_images',
        ),
    ]
