# Generated by Django 5.1.4 on 2024-12-18 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_description_alter_location_image'),
        ('orders', '0002_order_total_amount_alter_order_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
            preserve_default=False,
        ),
    ]
