# Generated by Django 5.1.4 on 2024-12-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_city_order_pincode_alter_order_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slot',
            field=models.CharField(choices=[('1-2', '1 PM - 2 PM'), ('2-3', '2 PM - 3 PM'), ('3:00 PM - 6:00 PM', '3:00 PM - 6:00 PM')], max_length=20),
        ),
    ]
