# Generated by Django 5.1.4 on 2024-12-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_slot'),
        ('packages', '0009_package_customizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customizations',
            field=models.ManyToManyField(related_name='orderCustomizations', to='packages.customization'),
        ),
    ]
