# Generated by Django 5.1.4 on 2024-12-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_customizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='location',
            new_name='locationId',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='package',
            new_name='packageId',
        ),
    ]
