# Generated by Django 5.1.4 on 2024-12-27 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_location_order_locationid_and_more'),
        ('packages', '0009_package_customizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customizations',
        ),
        migrations.CreateModel(
            name='OrderCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.customization')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
