# Generated by Django 5.1.4 on 2024-12-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_customizations_ordercustomization'),
        ('packages', '0009_package_customizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customizations',
            field=models.ManyToManyField(related_name='orders', through='orders.OrderCustomization', to='packages.customization'),
        ),
    ]
