# Generated by Django 5.1.4 on 2024-12-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_customizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercustomization',
            old_name='customization',
            new_name='customization_id',
        ),
    ]
