# Generated by Django 5.1.4 on 2024-12-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_customization_ordercustomization_customization_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercustomization',
            old_name='customization_id',
            new_name='customization_ins',
        ),
    ]
