# Generated by Django 5.1.4 on 2024-12-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_customization_id_ordercustomization_customization_ins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customizations',
        ),
    ]
