# Generated by Django 5.1.4 on 2024-12-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_customizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercustomization',
            old_name='customization_ins',
            new_name='customization',
        ),
    ]
