# Generated by Django 5.1.4 on 2024-12-29 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_customization_ins_ordercustomization_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercustomization',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='orders.order'),
        ),
    ]
