# Generated by Django 5.1.4 on 2024-12-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_ordercustomization_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('1-2', '1 PM - 2 PM'), ('2-3', '2 PM - 3 PM'), ('3:00 PM - 6:00 PM', '3:00 PM - 6:00 PM')], max_length=20, null=True),
        ),
    ]
