# Generated by Django 5.1.4 on 2024-12-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('new_order', 'New Order'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('accepted', 'Accepted'), ('completed_vendor', 'Completed Vendor'), ('completed_admin', 'Completed Admin'), ('declined', 'Declined')], max_length=20, null=True),
        ),
    ]
