# Generated by Django 5.1.4 on 2024-12-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new_order', 'New Order'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('accepted', 'Accepted'), ('completed_vendor', 'Completed Vendor'), ('completed_admin', 'Completed Admin'), ('declined', 'Declined')], default='new_order', max_length=20),
        ),
    ]
