# Generated by Django 5.1.4 on 2025-01-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new_order', 'New Order'), ('ongoing', 'Ongoing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed_mark_by_vendor', 'Completed Mark By Vendor'), ('completed_mark_by_admin', 'Completed Mark By Admin'), ('declined', 'Declined')], default='new_order', max_length=30),
        ),
    ]
