# Generated by Django 5.1.4 on 2025-01-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new_order', 'New Order'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('declined', 'Declined')], default='new_order', max_length=20),
        ),
    ]
